services:
  app:
    image: ghcr.io/dyrda1/expense-tracker:${GIT_COMMIT_HASH}
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:80"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://tempo:4317"
    secrets:
      - db_conn
    networks:
      - et_network
    entrypoint:
      - /bin/sh
      - -c
      - |
        export ConnectionStrings__Database=$$(cat /run/secrets/db_conn) &&
        dotnet ExpenseTracker.Web.dll
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
        parallelism: 1

  db:
    image: postgres:15.10
    environment:
      POSTGRES_DB: expense_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - et_network
    deploy:
      restart_policy:
        condition: on-failure

  db-backup:
    image: postgres:15.10
    depends_on:
      - db
    secrets:
      - db_password
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: expense_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - pg_backups:/backups
    networks:
      - et_network
    deploy:
      restart_policy:
        condition: on-failure
    entrypoint: >
      /bin/sh -c "trap exit TERM;
      while :; do pg_dump -h db -U postgres expense_tracker > /backups/db_backup_$$(date +%Y-%m-%d_%H-%M-%S).sql;
      sleep 24h & wait $${!}; done"

  nginx:
    image: nginx:stable-alpine3.20-perl
    ports:
      - "80:80"
      - "443:443"
    environment:
      BACKEND_HOST: app
      BACKEND_PORT: 80
    secrets:
      - nginx_htpasswd
    configs:
      - source: nginx_conf_template
        target: /etc/nginx/nginx.conf.template
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    networks:
      - et_network
    command: >
      /bin/sh -c "
      envsubst '$$BACKEND_HOST $$BACKEND_PORT' < /etc/nginx/nginx.conf.template > /etc/nginx/conf.d/default.conf &&
      nginx -g 'daemon off;'"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  certbot:
    image: certbot/certbot:v3.2.0
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    networks:
      - et_network
    entrypoint: >
      /bin/sh -c "trap exit TERM;
      while :; do certbot renew --webroot -w /var/www/certbot --quiet;
      sleep 12h & wait $${!}; done"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  prometheus:
    image: prom/prometheus:v3.2.0
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    volumes:
      - prometheus_data:/prometheus
    networks:
      - et_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  node-exporter:
    image: prom/node-exporter:v1.9.0
    networks:
      - et_network
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  loki:
    image: grafana/loki:3.4.2
    volumes:
      - loki_data:/loki
    configs:
      - source: loki_config
        target: /etc/loki/local-config.yaml
    networks:
      - et_network
    command: -config.file=/etc/loki/local-config.yaml
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  promtail:
    image: grafana/promtail:3.4.2
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
    configs:
      - source: promtail_config
        target: /etc/promtail/promtail.yaml
    command: -config.file=/etc/promtail/promtail.yaml
    networks:
      - et_network
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  tempo:
    image: grafana/tempo:r188-7336be4
    volumes:
      - tempo_data:/tmp/tempo
    configs:
      - source: tempo_config
        target: /etc/tempo/tempo.yaml
    command: -config.file=/etc/tempo/tempo.yaml
    networks:
      - et_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  grafana:
    image: grafana/grafana:11.5.2-ubuntu
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Editor"
      GF_EXPLORE_ENABLED: "true"
      GF_SERVER_ROOT_URL: "https://idyrda.site/grafana/"
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - et_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

secrets:
  db_password:
    external: true
  db_conn:
    external: true
  nginx_htpasswd:
    external: true

configs:
  nginx_conf_template:
    external: true
  prometheus_config:
    external: true
  loki_config:
    external: true
  promtail_config:
    external: true
  tempo_config:
    external: true

volumes:
  pgdata:
    external: true
  pg_backups:
    external: true
  certbot-www:
    external: true
  prometheus_data:
    external: true
  loki_data:
    external: true
  tempo_data:
    external: true
  grafana_data:
    external: true

networks:
  et_network:
    external: true