global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'expense-tracker'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'app:80' ]
  - job_name: 'node'
    static_configs:
      - targets: [ 'node-exporter:9100' ]